export function add(a: number, b: number): number {
    return a + b;
}
export type {
    Ability,
    AbilityFlags,
    SpeciesAbilitySlot,
    ApiResponse,
    BaseStats,
    DexDataset,
    DexSort,
    Evolution,
    LearnsetEntry,
    Machine,
    Move,
    PageResponse,
    Pokemon,
    PokemonType,
    SpeciesQuery,
    SpeciesDetails,
    SpeciesEvolution,
    SpeciesMachine,
    SpeciesType,
    SpeciesSprites,
    SpeciesFormInfo,
    FormGroupMember,
    FormChange,
    SpeciesFormGroup,
    Item,
    ItemPocket,
    RuleItem,
} from './dex.js';
